const chart = [
  [
    {
      id: 171,
      created_at: "2024-01-18T06:17:39.970493+00:00",
      contrat: "GCK",
      equipe: "D",
      mingzi: "噶当噶",
      nationalite: "CD",
      nom: "KATANGA",
      poste: "SUP",
      postnom: "KINYOSHI",
      prenom: "Amedee",
      section: "ENSACHAGE",
      phone: "",
      matricule: "L0278",
      chef_deq: "NON",
      list_priority: 0,
      tenue: "",
      pin: "0000",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME"],
      is_exp: "NON",
      lang: "en-US",
      rld: {
        rl: "-------------------------------",
        month_code: "mc_171_2024_9",
      },
    },
  ],
  [
    {
      id: 58,
      created_at: "2023-12-26T14:41:31.581926+00:00",
      contrat: "GCK",
      equipe: "D",
      mingzi: "卡已",
      nationalite: "CD",
      nom: "KAIJ",
      poste: "OPE",
      postnom: "A-MUTATSH",
      prenom: "",
      section: "ENSACHAGE",
      phone: "",
      matricule: "L0531",
      chef_deq: "OUI",
      list_priority: 1,
      tenue: "",
      pin: "0000",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME"],
      is_exp: "NON",
      lang: "en-US",
      rld: {
        rl: "-------------------------------",
        month_code: "mc_58_2024_9",
      },
    },
  ],
  [
    {
      id: 128,
      created_at: "2024-01-09T13:59:11.846912+00:00",
      contrat: "GCK",
      equipe: "D",
      mingzi: "莎米",
      nationalite: "CD",
      nom: "MUJINGA",
      poste: "OPE",
      postnom: "NKULU",
      prenom: "SAMI",
      section: "ENSACHAGE",
      phone: "",
      matricule: "L0565",
      chef_deq: "NON",
      list_priority: 5,
      tenue: "",
      pin: "0000",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME", "DIC"],
      is_exp: "NON",
      lang: "en-US",
      rld: {
        rl: "-------------------------------",
        month_code: "mc_128_2024_9",
      },
    },
    {
      id: 100,
      created_at: "2024-01-09T08:52:40.012781+00:00",
      contrat: "BNC",
      equipe: "D",
      mingzi: "卡伦博",
      nationalite: "CD",
      nom: "NGOY ",
      poste: "OPE",
      postnom: "KALOMBO ",
      prenom: "",
      section: "ENSACHAGE",
      phone: "",
      matricule: "",
      chef_deq: "NON",
      list_priority: 8,
      tenue: "",
      pin: "0000",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME"],
      is_exp: "NON",
      lang: "en",
      rld: {
        rl: "-------------------------------",
        month_code: "mc_100_2024_9",
      },
    },
    {
      id: 102,
      created_at: "2024-01-09T08:53:15.628315+00:00",
      contrat: "BNC",
      equipe: "D",
      mingzi: "",
      nationalite: "CD",
      nom: "KINYANYA ",
      poste: "OPE",
      postnom: "KALENGA",
      prenom: "",
      section: "ENSACHAGE",
      phone: "",
      matricule: "",
      chef_deq: "NON",
      list_priority: 10,
      tenue: "",
      pin: "0000",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME"],
      is_exp: "NON",
      lang: "en",
      rld: {
        rl: "-------------------------------",
        month_code: "mc_102_2024_9",
      },
    },
  ],
  [
    {
      id: 105,
      created_at: "2024-01-09T08:54:06.692473+00:00",
      contrat: "BNC",
      equipe: "D",
      mingzi: "卢福玛",
      nationalite: "CD",
      nom: "KAHILU ",
      poste: "CHARG",
      postnom: "LUFUMA",
      prenom: "",
      section: "ENSACHAGE",
      phone: "",
      matricule: "",
      chef_deq: "NON",
      list_priority: 14,
      tenue: "",
      pin: "0000",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME"],
      is_exp: "NON",
      lang: "en",
      rld: {
        rl: "-------------------------------",
        month_code: "mc_105_2024_9",
      },
    },
    {
      id: 260,
      created_at: "2024-10-03T15:48:14.750018+00:00",
      contrat: "BNC",
      equipe: "D",
      mingzi: "",
      nationalite: "CD",
      nom: "MUKENGE",
      poste: "CHARG",
      postnom: "FATAKI",
      prenom: "Jackson",
      section: "ENSACHAGE",
      phone: "",
      matricule: "",
      chef_deq: "NON",
      list_priority: 15,
      tenue: "",
      pin: "",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME"],
      is_exp: "NON",
      lang: "en",
      rld: {
        rl: "-------------------------------",
        month_code: "mc_260_2024_9",
      },
    },
    {
      id: 107,
      created_at: "2024-01-09T08:54:36.866679+00:00",
      contrat: "BNC",
      equipe: "D",
      mingzi: "科萨伊",
      nationalite: "CD",
      nom: "EKOSAYI ",
      poste: "CHARG",
      postnom: "MONIMAMBO  ",
      prenom: "",
      section: "ENSACHAGE",
      phone: "",
      matricule: "",
      chef_deq: "NON",
      list_priority: 16,
      tenue: "",
      pin: "0000",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME"],
      is_exp: "NON",
      lang: "en",
      rld: {
        rl: "-------------------------------",
        month_code: "mc_107_2024_9",
      },
    },
    {
      id: 261,
      created_at: "2024-10-10T08:29:22.028891+00:00",
      contrat: "BNC",
      equipe: "D",
      mingzi: "",
      nationalite: "CD",
      nom: "KATEMBU",
      poste: "CHARG",
      postnom: "TSHIMBALANGA",
      prenom: "Daniel",
      section: "ENSACHAGE",
      phone: "",
      matricule: "",
      chef_deq: "NON",
      list_priority: 100,
      tenue: "",
      pin: "",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME"],
      is_exp: "NON",
      lang: "en",
      rld: {
        id: 600,
        created_at: "2024-11-14T20:14:54.379632+00:00",
        rl: "-------------------------------",
        month_code: "mc_261_2024_9",
        agent_id: 261,
      },
    },
    {
      id: 264,
      created_at: "2024-10-22T05:47:35.139395+00:00",
      contrat: "BNC",
      equipe: "D",
      mingzi: "",
      nationalite: "CD",
      nom: "MUKALA",
      poste: "CHARG",
      postnom: "MPUETO",
      prenom: "Stanny",
      section: "ENSACHAGE",
      phone: "",
      matricule: "",
      chef_deq: "NON",
      list_priority: 100,
      tenue: "",
      pin: "",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME"],
      is_exp: "NON",
      lang: "en",
      rld: {
        id: 602,
        created_at: "2024-11-14T22:58:19.907031+00:00",
        rl: "-------------------------------",
        month_code: "mc_264_2024_9",
        agent_id: 264,
      },
    },
  ],
  [
    {
      id: 210,
      created_at: "2024-04-18T16:13:48.074457+00:00",
      contrat: "BNC",
      equipe: "D",
      mingzi: "",
      nationalite: "CD",
      nom: "NJIBU",
      poste: "NET",
      postnom: "MWANA",
      prenom: "Meil",
      section: "ENSACHAGE",
      phone: "",
      matricule: "",
      chef_deq: "NON",
      list_priority: 100,
      tenue: "",
      pin: "0000",
      user_level: 0,
      active: "OUI",
      photo: null,
      access_codes: ["HME"],
      is_exp: "NON",
      lang: "en",
      rld: {
        rl: "-------------------------------",
        month_code: "mc_210_2024_9",
      },
    },
    {
      id: 222,
      created_at: "2024-04-30T06:42:09.8364+00:00",
      contrat: "BNC",
      equipe: "D",
      mingzi: "",
      nationalite: "CD",
      nom: "CIZANGA",
      poste: "NET",
      postnom: "CIZANGA",
      prenom: "Jonathan",
      section: "ENSACHAGE",
      phone: "0892695138",
      matricule: "BNC100",
      chef_deq: "NON",
      list_priority: 100,
      tenue: "",
      pin: "0000",
      user_level: 0,
      active: "OUI",
      photo:
        "https://ltvavdcgdrfqhlfpgkks.supabase.co/storage/v1/object/public/agents_photos/1719478709397.jpeg",
      access_codes: ["HME", "RLDS", "UPDL", "ANL", "DELL"],
      is_exp: "OUI",
      lang: "en",
      rld: {
        rl: "-------------------------------",
        month_code: "mc_222_2024_9",
      },
    },
  ],
];

export default chart;
